- BahaTurret/BDArmorySettings.cs
- BahaTurret/BulletInfo.cs
- BahaTurret/Distribution/GameData/BDArmory/Parts/50CalTurret/50cal.cfg
- BahaTurret/Distribution/GameData/BDArmory/bullets.cfg
- BahaTurret/ModuleWeapon.cs
- BahaTurret/PooledBullet.cs
> Feature bullet penetration

- BahaTurret/ArmorPenetration.cs
- BahaTurret/BDArmor.cs
- BahaTurret/Distribution/GameData/BDArmory/MMPatches/squad_tanks.cfg
- BahaTurret/Distribution/GameData/BDArmory/bullets.cfg
- BahaTurret/PooledBullet.cs
Some code looks like
`public enum PooledBulletTypes{Standard, Explosive}`
after visual studio automatic indenting
`public enum PooledBulletTypes { Standard, Explosive }`
```
public Vessel sourceVessel;
public Color lightColor = Misc.ParseColor255("255, 235, 145, 255");
public Color projectileColor;
//some other code
public Color lightColor = Misc.ParseColor255("255, 235, 145, 255");
```
So that's the reason of "It seems that big pieces of code have been removed and then pasted again"
I really have no way to solve it.
we need to really solve these problems.
> Feature armor

- BahaTurret/MissileFire.cs
- BahaTurret/MissileLauncher.cs
- BahaTurret/MissileTurret.cs
- BahaTurret/ModuleRadar.cs
- BahaTurret/ModuleWeapon.cs
Additional Features:
- show right-mouse-button information in editor (VAB/SPH) for guns, missiles and radar
Fixes:
- for air-ground missiles, prevent firing full complement at once (respect maxMissilesTarget)
- prevent gps guided missiles being used on air targets/incoming missiles
- try to improve selection of AA missiles/guns against incoming missiles
> AI Improvements for AA/AG - Support Branch

- BahaTurret/BDArmory.csproj
- BahaTurret/Misc/BahaTurretBullet.cs
- BahaTurret/MissileLauncher.cs
- BahaTurret/Parts/BDModularGuidance.cs
- BahaTurret/Parts/MissileBase.cs
Adding files to csproj			8bf954f
Fixing compilation errors of BahaTurretBullet			3901ae3
Fixing max off boresight UI
> small fixes

- BahaTurret/Control/BDModulePilotAI.cs
> Min altitude attitude control fix

- .gitignore
- BDArmory/BDArmory.csproj
- BDArmory/Misc/EngageableWeapon.cs
- BDArmory/MissileFire.cs
- BDArmory/Parts/BDModularGuidance.cs
> Several improvements for modular missiles 

- BDArmory/UI/BDATargetManager.cs
FIX: problems with laser targeting
FIXES #187
FIXES #216
> Fixing problems with laser targeting

- BDArmory/LoadedVesselSwitcher.cs
> fixing issue with throttle mirroring when switching vessels

- BDArmory/Distribution/GameData/BDArmory/Parts/ArmorPlate/BD1x1panelArmor.cfg
- BDArmory/Distribution/GameData/BDArmory/Resources/Armor.cfg
Default BDA Armor panels made working with my new armor penetration system...
> Armor Panel Update

- BDArmory.Core/Extension/PartExtensions.cs
- BDArmory.Core/Module/DamageTracker.cs
- BDArmory/FX/BulletHitFX.cs
- BDArmory/FX/ExplosionFX.cs
- BDArmory/Misc/BDAEditorCategory.cs
- BDArmory/PooledBullet.cs
further balancing , stopping lower caliber rounds after first penetration
Merged dev branch fixes and compiled against 1.3.1
> Feature armor sync

- BDArmory/Control/BDACompetitionMode.cs
- BDArmory/Control/ModuleWingCommander.cs
- BDArmory/CounterMeasure/CMFlare.cs
- BDArmory/FX/BulletHitFX.cs
- BDArmory/FX/ExplosionFX.cs
- BDArmory/Misc/BDAExtensions.cs
- BDArmory/Misc/Misc.cs
- BDArmory/MissileFire.cs
- BDArmory/MissileTurret.cs
- BDArmory/ModuleWeapon.cs
- BDArmory/Parts/BDRotaryRail.cs
- BDArmory/Parts/ClusterBomb.cs
- BDArmory/Parts/MissileLauncher.cs
- BDArmory/RocketLauncher.cs
- BDArmory/Shaders/BDAShaderLoader.cs
- BDArmory/UI/BDAPersistantSettingsField.cs
- BDArmory/UI/BDAWindowSettingsField.cs
Change from ToList to AsEnumerable
> Performance improvements!

- BDArmory/Distribution/GameData/BDArmory/Localization/localization-zh-cn.cfg
> Chinese part localization

- BDArmory/MissileFire.cs
Suggested fix #400 by using safe casting and null check.
> Guard mode fairing fix

- BDArmory/Guidances/CruiseGuidance.cs
- BDArmory/Parts/BDModularGuidance.cs
- BDArmory/Parts/MissileBase.cs
Better terrain checks and prediction times
> Dev cruise guidance

- BDArmory/Distribution/GameData/BDArmory/ChangeLog.txt
Add a changelog line to document floating origin/krakensbane fixes to bullets and pilot AI
> Floating origin bugfix changelog

- BDArmory/Bullets/PooledBullet.cs
Remove bullet collision disable for the first frame. Couldn't figure out why it was there in the first place, tbh, and it was interfering with kerbal CQC. :)
Also removed the unused `prevPosition` variable while I was at it. :)
> fix bullets not hitting extremely close targets

- BDArmory/Misc/VectorUtils.cs
I don't think it affects anything significantly, but I felt really bad about this one. :)
> change sqrt2 not to be 1

- BDArmory/Control/BDAirspeedControl.cs
Full throttle when no power is available but desired acceleration is >0
Should let the AI sort of use engines it is not specifically made for.
> AI APU adaptation

- BDArmory/Control/BDModulePilotAI.cs
add a couple of aiming lines to pilotAI
the red one is where it is trying to aim, the white one is where the aircraft is actually pointing at
adjust pilot steering (mostly add a bit of pitchKi) until the lines start to match ;)
> aiming debug lines

- .gitignore
- BDArmory/FX/ExplosionFX.cs
- BDArmory/Modules/BDModularGuidance.cs
- BDArmory/Modules/BDModulePilotAI.cs
- BDArmory/Modules/BDModuleSurfaceAI.cs
- BDArmory/Modules/ClusterBomb.cs
- BDArmory/Modules/MissileFire.cs
- BDArmory/Modules/MissileLauncher.cs
- BDArmory/Modules/ModuleWeapon.cs
- BDArmory/Modules/RocketLauncher.cs
- Update Ki component of PAI PID controller to correct for persistent aiming errors #565 
- Fix bombs away calculation so guard mode obeys the missiles/tgt variable #567 
- Add a roll check so guard mode does not throw bombs when upside down #567 
- Add Krakensbane corrections to cluster bomb munitions, rockets and explosions #171 
- Add orbit direction selectors for surface and pilot AI #403 
- Set autofire error to zero for turrets. Update order of updates for guns so firing happens right after aiming turrets. #497
> AI and misc fixes

- BDArmory/Distribution/GameData/BDArmory/Localization/localization-zh-cn.cfg
The new BDAEditorCategory module just read the English version of part's manufacturer.
Revert it to English version simply fixes the issue.
> Workaround for issue #580

- BDArmory/Modules/EngageableWeapon.cs
- BDArmory/Modules/MissileFire.cs
- BDArmory/Modules/ModuleWeapon.cs
Implements ability to assign weapons to weapon groups for both manual and AI use. 
Changes to MissileFire - AI weapon selection edits to get it to pull from created weapon groups.
Changes to ModuleWeapon - Weapongroups GUI implementation.
Changes to EngageableWeapon - Shifted ShortName() to here,
Merge PR #1 & 2 is just me merging individual .cs edits into one branch.
> Feature: Weapon Groups

- BDArmory/Modules/ModuleWeapon.cs
- Only extrapolate acceleration in the direction of travel.
- Cap extrapolated acceleration to a doubling of speed.
Both for non-orbiting craft only.
This should improve accuracy when firing on bobbing ships and maneuvering planes, as ballistics won't assume that the current acceleration will continue forever.
> Acceleration extrapolation updates

- BDArmory/Modules/MissileTurret.cs
> missile turrets no longer bypass drop time

- BDArmory/Targeting/TargetInfo.cs
Fix wrong capitalization on `isCommandable`.
> fix capitalization

- BDArmory/Misc/VectorUtils.cs
- BDArmory/Modules/ModuleWeapon.cs
Turns out I never merged the correct bullet spread distribution...
> Rayleigh deviation for bullet spread

- BDArmory/Modules/BDModularGuidance.cs
- BDArmory/Modules/MissileBase.cs
- BDArmory/Modules/MissileFire.cs
- BDArmory/Modules/MissileLauncher.cs
Allow changing the clearance radius for specific munitions in part config
> Clearance enhancements

- BDArmory/Modules/MissileFire.cs
Reverts PapaJoesSoup/BDArmory#619
wrong branch :(
> Revert "Fix for ripple fire"

- BDArmory/Modules/MissileFire.cs
Recreate #619 for the dev branch
> Suicidal insanity ripple fix

- BDArmory/Distribution/GameData/BDArmory/ChangeLog.txt
Include SuicidalInsanity's changes
> update changelog for SuicidalInsanity's changes

- BDArmory/Modules/ModuleWeapon.cs
- BDArmory/UI/BDATargetManager.cs
Fix messed up safety check from teams refactor.
Also slightly improve performance of weapons simulation.
> Fix safety check

- BDArmory/Control/BDACompetitionMode.cs
- BDArmory/Modules/ModuleWingCommander.cs
Add formation parameters back to SPH/VAB
> Bring back formation parameters

- BDArmory/Radar/VesselRadarData.cs
> fix swapped radar lock icons

- BDArmory/Modules/MissileFire.cs
- BDArmory/UI/BDArmorySetup.cs
> fix missile turret turning off

- BDArmory/Misc/Misc.cs
- BDArmory/Modules/ModuleWeapon.cs
- BDArmory/UI/KrakensbaneDebug.cs
Improving turret accuracy a bit (yes, it's almost a complete rewrite of the prediction alogrithm :)
> Turret accuracy tweaks

- BDArmory/Radar/RadarUtils.cs
> Fix ignoring targets in front of you.

- BDArmory/Bullets/PooledBullet.cs
> fix drag calculation to not increase bullet speed anymore

- BDArmory/Distribution/GameData/BDArmory/ChangeLog.txt
- BDArmory/Modules/ModuleMissileRearm.cs
> Fix reloadable rail ammo limitation

- BDArmory/Modules/MissileFire.cs
Rewritten using latest version of MissileFire.cs
> Expanded SmartPick weapon selection

- BDArmory/Modules/MissileBase.cs
- BDArmory/Modules/MissileFire.cs
- BDArmory/Modules/ModuleWeapon.cs
Missiles will now display #remaining in the Weapon Manager GUI, and Guns will display ammo count. Heterogeneous weapon groups will display ammo totals per ammo type used in the group
> Add munitions count to WM GUI; #191

- BDArmory/Modules/MissileLauncher.cs
Torpedoes will no longer work like missiles above water
> Torpedo fix for #710

- BDArmory/Distribution/GameData/BDArmory/BulletDefs/BD_Bullets.cfg
- BDArmory/Distribution/GameData/BDArmory/Parts/SaturnAL31/SaturnAL31.cfg
- BDArmory/Distribution/GameData/BDArmory/Parts/SaturnAL31/SaturnAL31_TS.cfg
- BDArmory/Distribution/GameData/BDArmory/Parts/browninganm2/browninganm2.cfg
Adjustment of the weight of the Saturn AL-31 engine, and a slight change to the thrust.
> Changes to the Saturn engine and .50 cal rounds
