BahaTurret/Distribution/GameData/BDArmory/Parts/agm-86Cruise/agm86.cfg, BahaTurret/Distribution/GameData/BDArmory/Parts/aim-120/amraam.cfg, BahaTurret/Distribution/GameData/BDArmory/Parts/clusterBomb/clusterBomb.cfg, BahaTurret/Distribution/GameData/BDArmory/Parts/harm/harm.cfg, BahaTurret/Distribution/GameData/BDArmory/Parts/hekv1/hekv1.cfg, BahaTurret/Distribution/GameData/BDArmory/Parts/hellfireMissile/hellfireMissile.cfg, BahaTurret/Distribution/GameData/BDArmory/Parts/jdamMk83/jdam.cfg, BahaTurret/Distribution/GameData/BDArmory/Parts/maverick/maverickMissile.cfg, BahaTurret/Distribution/GameData/BDArmory/Parts/mk82Bomb/mk82Bomb.cfg, BahaTurret/Distribution/GameData/BDArmory/Parts/mk82BombBrake/mk82BombBrake.cfg, BahaTurret/Distribution/GameData/BDArmory/Parts/pac-3/pac3.cfg, BahaTurret/Distribution/GameData/BDArmory/Parts/rbs-15/rbs15.cfg, BahaTurret/Distribution/GameData/BDArmory/Parts/sidewinder/sidewinder.cfg, BahaTurret/Distribution/GameData/BDArmory/Parts/towMissile/towMissile.cfg
I am not experienced with modding, but cost values were really weird so I decided to change them in case somebody wants to make a career-mode war DMP server :D 
They are, in general, 1/500 of the real cost values in present-day US dollars. However, many of them have different values for various gameplay reasons. I didn't want a very hardcore approach, so the missiles don't cost more than aircraft, but I think that at least for air-air missiles, the cost should encourage people to use guns whenever missiles are not needed, at least on career war servers ;)
Do you agree with my values, or should I change something?
=> Missile cost rebalance

BahaTurret/Distribution/GameData/BDArmory/Parts/20mmVulcan/vulcanTurret.cfg, BahaTurret/Distribution/GameData/BDArmory/Parts/hiddenVulcan/hiddenVulcan.cfg
Fixed Vulcan mass change from 0.3 to 0.1, turret Vulcan mass change from 0.4 to 0.2. Both used to be unrealistically high, moreover, the CoM shift when mounting Vulcan on the front of a plane could seriously impact maneuverability or even flyability, this way it's much less problematic.
BTW the turret vulcan is heavier than normal cuz the turret rotation mechanism and such stuff has to add some mass to the gun, also cuz balance.
=> Vulcan mass changes

BDArmory/MissileLauncher.cs
Fix bug with terminal guidance, re-check engagement envelope when switching to terminal guidance mode (dont radar just something, only appropriate targets)
=> Fix terminal guidance bug

BDArmory/ModuleWeapon.cs, BDArmory/TargetSignatureData.cs
1. fix nullrefs when switching to terminal radar guidance
2. fix nullrefs with weapons without staging icons overheating
=> Fixing nullrefs

BDArmory/FX/ExplosionFX.cs, BDArmory/PooledBullet.cs
Explosion force fix (no more 30mm gauss cannon knocking 100t tanks around like golf balls) and minor edit to damage transfer to stop things from spontaneously exploding when something like spaced armor is struck
=> Explosion force fix and minor edit to damage transfer to stop things from spontaneously exploding when something like spaced armor is struck

BDArmory/Misc/BDAEditorCategory.cs
This will fix the BDArmory tab not showing on KSP 1.3.1
=> Fix for KSP 1.3.1

BDArmory/Control/BDAirspeedControl.cs
Little fix for drag estimation - current results in rolling off the throttle in a climb even when below target speed.
* Used vessel.VelocityD instead of the craft transform; while this normally makes things more accurate I'm a little concerned about what will happen if the craft's velocity vector is way off it's nose, say for post-stall supermaneuverable craft. I don't have any to test with. Hopefully that is the right velocity vector too... docs are thin on the ground there. Reason is simply to cope with angle of attack.
* Used scalar projection in GravAccel() just to make it a bit simpler
* Estimated drag now takes current gravity drag into account - this fixes backing off throttle in a climb.
* Using vessel.acceleration_immediate to avoid transient changes resulting in unwanted …
=> Fix for #305 - drag estimations

BDArmory/Control/BDModulePilotAI.cs
pilotAI disengages standby only after a target has been actually detected by itself or another friendly
=> fixes #406

BDArmory/UI/BDArmorySetup.cs
Checks if module manager and physics range extender are loaded and, if they are not loaded, displays a big warning when weapon manager toolbar is open.
=> Dependency check error

BDArmory/FX/BDAParticleSelfDestruct.cs, BDArmory/Radar/ModuleRadar.cs
Note: this makes BDA dev branch TECHNICALLY compatible with KSP 1.4 as of avoiding compilation and runtime exceptions.
Most likely still needs work to make it BEHAVE correctly with 1.4, especially regarding:
- radar rcs shader seems to be affected
- potentially particle emitters need to be checked for correct function
=> KSP 1.4 changes to avoid compilation & runtime errors

BDArmory/MissileFire.cs, BDArmory/Parts/ModuleECMJammer.cs, BDArmory/Radar/ModuleRadar.cs
At some point I made MissileFire refresh modules on start ( https://github.com/PapaJoesSoup/BDArmory/blame/dev/BDArmory/MissileFire.cs#L749 ). 
Since previously it didn't do that, modules were adding themselves to the MissileFire lists on load, which resulted in them appearing in the module list twice. :)
=> Fix #481 modules appearing in weapon manager module list twice

BDArmory/MissileFire.cs, BDArmory/RocketLauncher.cs, BDArmory/UI/BDArmorySetup.cs
Make rocket pods and turrets obey `INFINITE_AMMO` setting.
When it's on, rockets are no longer used up, and empty rocket pods can be fired.
Empty rocket pods will also appear in the weapon list on list update, but toggling `INFINITE_AMMO` does not force an update.
related to #533
=> Infinite ammo for rockets

BDArmory/Control/BDModulePilotAI.cs
Allow setting PilotAI tuning to ridiculous values in game.
Also increase max value of maxG to 45 according to #528
related to #528
=> add a tuning unclamper for PilotAI

BDArmory.Core/Extension/PartExtensions.cs, BDArmory/Misc/VectorUtils.cs, BDArmory/Modules/ModuleWeapon.cs
- Use the correct formula for calculating normal distribution #571
- `maxDeviation` is now actually two standard deviations, which seems to be in line with previous bullet spread
- Fixed a check for Tweakscale throwing errors like crazy when no Tweakscale is present.
- Multiple the config rpm by number of fire transforms for info display #524 
- Weapons may fire multiple times per update #524
=> Normal distribution

BDArmory/Modules/MissileBase.cs, BDArmory/Modules/MissileFire.cs, BDArmory/Radar/RadarUtils.cs, BDArmory/Targeting/TargetInfo.cs, BDArmory/UI/BDATargetManager.cs
AI can now blow itself up with torpedoes like a boss, that is, this should fix AI weapon selection for splashed targets to include torpedoes.
Also renamed TargetInfo.isLanded to what it actually is.
=> Guard mode torpedo fix

BDArmory.Core/BDArmorySettings.cs, BDArmory/Misc/WMTurretGroup.cs, BDArmory/Modules/MissileFire.cs, BDArmory/Modules/MissileLauncher.cs, BDArmory/Modules/ModuleWeapon.cs, BDArmory/Modules/RadarWarningReceiver.cs, BDArmory/Radar/RadarUtils.cs, BDArmory/UI/BDArmorySetup.cs
- Entering a blank weapon group will now nicely reset the weapon name to the original one.
- Legacy targeting is gone.
- Guard mode "scanning" is gone, now it checks the whole view angle cone at once.
- BDA "Physics range" is gone.
=> Weapon groups reset and remove deprecated features

BDArmory/BDArmory.csproj, BDArmory/Control/BDACompetitionMode.cs, BDArmory/Distribution/GameData/BDArmory/ChangeLog.txt, BDArmory/Misc/BDTeam.cs, BDArmory/Misc/Misc.cs, BDArmory/Modules/BDGenericAIBase.cs, BDArmory/Modules/BDModularGuidance.cs, BDArmory/Modules/BDModulePilotAI.cs, BDArmory/Modules/MissileBase.cs, BDArmory/Modules/MissileFire.cs, BDArmory/Modules/MissileLauncher.cs, BDArmory/Modules/ModuleTargetingCamera.cs, BDArmory/Modules/ModuleWingCommander.cs, BDArmory/Parts/GPSTargetInfo.cs, BDArmory/Radar/RadarUtils.cs, BDArmory/Radar/VesselRadarData.cs, BDArmory/Targeting/TargetInfo.cs, BDArmory/Targeting/TargetSignatureData.cs, BDArmory/UI/BDATargetManager.cs, BDArmory/UI/BDArmorySetup.cs, BDArmory/UI/BDTeamSelector.cs, BDArmory/UI/LoadedVesselSwitcher.cs
Adds functionality to have more than two teams in BDA.
- BDTeam is now uniformly an `object` (removing both the `bool` and the `enum` team types).
- Teams are fully customizable and saved with the craft.
- Custom team names (`A` and `B` are ghost-hardcoded so the `Next team` button always switches between at least two teams).
- Teams can be `Neutral` (no UI, `Neutral` team is hardcoded to be neutral).
- Teams can be set to be friendly toward other teams (currently no option to set this in the UI).
- Updated vessel switcher to accomodate more teams.
- Updated infrastructure to accomodate more teams (`TargetInfo`, target databases, gps database, etc.)
- Added team selection dropdown (right click the team button in weapon manager or vessel switcher.
=> Feature: Multiple teams

BDArmory/Modules/MissileFire.cs
My initial change to permit accurate weapon group weapon rpm count forgot to also change the timeDelayPerGun calc, resulting in the time delay now grabbing the square of total rpm, which causes Barrage to be essentially identical to Salvo, rather than correctly ripple firing linked weapons if Barrage mode is selected.
=> Fix for ripple fire

BDArmory/Modules/BDModulePilotAI.cs
Stop PAI throwing nullrefs when evasive if rwr ends up being missing
=> catch rwr nullref on evasive PAI

BDArmory/UI/BDArmorySetup.cs
Must still be positive, otherwise the square distance check will go very wrong.
=> unclam competition distance

BDArmory/Distribution/GameData/BDArmory/ChangeLog.txt, BDArmory/Misc/VectorUtils.cs, BDArmory/Modules/MissileFire.cs, BDArmory/Modules/ModuleTurret.cs
Should mostly fix #614 
Turrets may still freak out for targets behind the turret and between the end of the barrel and turret center, but that is such and edge case that we may allow it to persist.
Also fix calculation of gimbal in-range targets.
=> Turret rotation fix

BDArmory/Modules/ModuleWeapon.cs
Fix for multiple weapons of one type with different max ranges to respect individual weapon's range settings, rather than all firing as soon as one of them comes in range
=> Weapons respect engagement range

BDArmory/Distribution/GameData/BDArmory/Localization/BDArmory.cfg, BDArmory/Modules/ModuleRadar.cs
There is an unused localization file with some incorrect syntax. It appears that this was created in #253 along with some C# code to use it (790aae5ab70ba1a859a36e54ffb5e916b9c10c12), but the C# code was lost later in that PR and did not make it to the release. (Noticed thanks to KSP-CKAN/CKAN#2816.)
This pull request fixes the syntax in the .cfg file (the token for substituting a value is `<<1>>` instead of `{0}`, see http://lingoona.com/cgi-bin/grammar#l=en&oh=1), adds several missing strings that were added in the meantime, and re-adds the C# localization changes that use them.
=> Localization fixes

BDArmory/Distribution/GameData/BDArmory/Parts/ABL/ABL.cfg, BDArmory/Modules/ModuleWeapon.cs
- Fix laser renderer to only render out to effective distance.
- Clamp AI range to not fire beyond effective distance.
- Set ABL range to the default 5000.
=> fix laser distance

BDArmory/Distribution/GameData/BDArmory/Parts/SaturnAL31/SaturnAL31.cfg
Mistakenly left the CoMOffset commented out.
The new CoMOffset will make it so that if you go from the Squad Panther engine to the Saturn, it should not change your COM much at all.
=> Fixed CoMOffset on Saturn engine
